version: '3.9'

services:
  mariadb:
    container_name: db
    image: mariadb:10.7
    ports:
      - 3306:3306
    volumes:
      - /db_volume:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=PASSWORD
      - MYSQL_DATABASE= app_db #OPTIONAL
      - MYSQL_USER= db_user #OPTIONAL
      - MYSQL_PASSWORD= db_user_pass
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: #USER e.g root
      PMA_PASSWORD: #PASSWORD e.g MYSQL_ROOT_PASSWORD
      PMA_ARBITRARY: 1
    restart: always
    ports:
    - 8081:80